---

name: CI

on:
  pull_request:
    branches: main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-python@v5.0.0
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files
